// <auto-generated />
using BPLS.CadastroVeiculo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BPLS.CadastroVeiculo.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("BPLS.CadastroVeiculo.Dominio.Entities.Modelo", b =>
                {
                    b.Property<long>("IdModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("IdModelo");

                    b.ToTable("Modelos");

                    b.HasData(
                        new
                        {
                            IdModelo = 1L,
                            Descricao = "FH"
                        },
                        new
                        {
                            IdModelo = 2L,
                            Descricao = "FM"
                        });
                });

            modelBuilder.Entity("BPLS.CadastroVeiculo.Dominio.Entities.TipoVeiculo", b =>
                {
                    b.Property<long>("IdTipoVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("IdTipoVeiculo");

                    b.ToTable("TiposVeiculo");

                    b.HasData(
                        new
                        {
                            IdTipoVeiculo = 1L,
                            Descricao = "Caminhão"
                        });
                });

            modelBuilder.Entity("BPLS.CadastroVeiculo.Dominio.Entities.Veiculo", b =>
                {
                    b.Property<long>("IdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("INT");

                    b.Property<int>("AnoModelo")
                        .HasColumnType("INT");

                    b.Property<long>("IdModelo")
                        .HasColumnType("bigint");

                    b.HasKey("IdVeiculo");

                    b.HasIndex("IdModelo");

                    b.ToTable("Veiculos");

                    b.HasData(
                        new
                        {
                            IdVeiculo = 1L,
                            AnoFabricacao = 2021,
                            AnoModelo = 2021,
                            IdModelo = 1L
                        });
                });

            modelBuilder.Entity("BPLS.CadastroVeiculo.Dominio.Entities.Veiculo", b =>
                {
                    b.HasOne("BPLS.CadastroVeiculo.Dominio.Entities.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("IdModelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modelo");
                });
#pragma warning restore 612, 618
        }
    }
}
